name: Docker Image - arm64v8

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: [self-hosted, linux, ARM64]

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        run: |
          set -eux
          make docker_build_arm64v8
          make docker_push_arm64v8
          make docker_push_manifest_arm64v8
