name: Docker Image

on:
  push:
    branches: [ master ]

jobs:
  build_amd64:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        run: |
          set -eux
          make docker_build_amd64
          make docker_push_amd64
          make docker_push_manifest_amd64
  build_arm64v8:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        run: |
          set -eux
          make docker_build_arm64v8
          make docker_push_arm64v8
          make docker_push_manifest_arm64v8
